### ISSUE TITLE
Check email syntax on update request

### ISSUE THREAD

**Issue by sebastienbarbier** [sebastienbarbier/seven23_server#17]
Entry point `/api/v1/users/email` should check if provided value has an email syntax and return appropriate error message otherwise.
Right now, it seams to accept any string without

**Comment by mavhungutrezzy** [comment]
Hi, Could you please confirm if this issue has been addressed?

**Comment by sebastienbarbier** [comment]
It has not been addressed yet, low priority as front-end handle the syntax error for now.

**Comment by sebastienbarbier** [comment]
Thank you so much @mavhungutrezzy for your contribution, this has been released as part of [release v1.5.1](https://github.com/sebastienbarbier/seven23_server/releases/tag/v1.5.1).
