### ISSUE TITLE
Add deployment using Docker

### ISSUE THREAD

**Issue by sebastienbarbier** [sebastienbarbier/seven23_server#21]
One common request is adding support for Docker to facilitate deployment 🚀. There is no reason not to do it.

Server code currently use the one command deployment concept, which allow easy build and run on cloud plateform. It seams important to keep this as an option to keep current stack.

Current installation process can be find on [seven23_server online documentation](https://seven23-server.readthedocs.io/en/latest/installation.html)

**Comment by niwo** [comment]
Hi!

I added docker and docker-compose files for the project, see #23 

Open Issues:
- serving static assets should be done with a separate webserver (i.e. nginx).
  currently the server is started with "manage.py runserver  --insecure"
- Signup from the webapp does not seem to work, but I couldn't figure out why.
  You can see HTTP 404 log entries when trying to access "POST /api/v1/rest-auth/registration/ HTTP/1.1" on the backend

**Comment by Natim** [comment]
For some reason it became `POST /api-token-auth`

**Comment by sebastienbarbier** [comment]
By default, registration is not public. I assumed people self hosting a server instance would like to keep it private. Like @Natim said, `ALLOW_ACCOUNT_CREATION=True` solve this. Also `ALLOW_ACCOUNT_CREATION` is send on `"GET /api/init/ HTTP/1.1"` to enable/disable UI in seven_23/webapp.

This however create an issue, how do you create the first user account on initialisation. I would say not implemented yet, for now admin need to enable, create a user, then disable. Not great.

One solution would be to have a kind of wizard on install to guide the user. If just installed - coul dbe detected if there is no none-admin users - we display the wizard. An issue has been created (#24)

**Comment by Natim** [comment]
> how do you create the first user account on initialisation

I would recommend creating a django command for that.

`python manage.py createfirstuser`
