### ISSUE TITLE
Add recursive transactions

### ISSUE THREAD

**Issue by sebastienbarbier** [sebastienbarbier/seven23_server#26]
Implement a data structure to store recursive transactions.
Need to be tested with unittest.

**Comment by nykroy** [comment]
Great idea!

**Comment by sebastienbarbier** [comment]
Currently fixing major bugs, as soon as those are fixed this will be the first new features to be added 👍

**Comment by sebastienbarbier** [comment]
Recurrent transaction will use same data model as transactions and not need any update on frontend side.
Task will be implemented front-end, more details can be found on the coresponding issue : https://github.com/sebastienbarbier/seven23/issues/30

**Comment by sebastienbarbier** [comment]
@nykroy recurrent transaction have been added yesterday to seven23 webapp https://github.com/sebastienbarbier/seven23/pull/37
Still a first version on term of UI there is a general refactoring / rebranding coming next in my todolist but have been using it for couple weeks and should work for now. Just wanted to keep you updated, sorry for taking so long always difficult to find time to maintain side projects 😅
