### ISSUE TITLE
Everything django is broken

### ISSUE THREAD

**Issue by fabian310** [sebastienbarbier/seven23_server#28]
It seems like everything related to django is pretty much broken (I do not have personal experience with django, I tried to fix it myself).

First error when executing `python manage.py migrate`:
>django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.  

Second error when executing `python manage.py migrate` and add something like `os.environ.setdefault("SECRET_KEY", "k3-=2r(yq-towhfr-$@am&p%ze_&1!m!n7h2p%6*=fn4nr$=d^")` to manage.py:
> django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.

**Comment by Natim** [comment]
You need to create a settings.py file from the example.

**Comment by sebastienbarbier** [comment]
Both issue seams to be related to the missing `SECRET_KEY`. If you look at the [settings.py](https://github.com/sebastienbarbier/seven23_server/blob/master/seven23/settings.py#L30) such value needs to be defined as an environment variable.

I have just rerunned our [test pipe on travis](https://travis-ci.org/github/sebastienbarbier/seven23_server) and it is all green so no issue on our side I would say.

You can see in [manage.py](https://github.com/sebastienbarbier/seven23_server/blob/master/manage.py) we use the [loaddotenv](https://pypi.org/project/python-dotenv/) library

```
from dotenv import load_dotenv
load_dotenv()
```
You can set within seven23 a .env file with a secret key same as django usually do :) 

This should be mentioned within installation documetnation, will update later to make sure no one else have the issue.

**Comment by fabian310** [comment]
This should definitely be mentioned in the docs so people like me, with no django knowledge, at least know where the error is.
Thank You for the explanation and the documentation update!
